### PR TITLE
Rename Microsoft.Runtime.Abstractions to Microsoft.Extensions.Platfor…

### PR DESCRIPTION
**Pull request by Mitch528**
Rename Microsoft.Runtime.Abstractions to Microsoft.Extensions.PlatformAbstractions

### CODE REVIEW

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/SignalR-Server/pull/130, but thank you!

**Comment by Mitch528** [comment]
No problem, although technically mine was first.

**Comment by Eilon** [comment]
@Mitch528 yep I saw that, I figured @pakrym can get his change in quicker though. Appreciate the effort!

**Comment by Mitch528** [comment]
Ah, okay. It doesn't matter, as long as it gets done :).

**Pull request closed without merging**
