### PR TITLE
Changes to use generations TFM and added Microsoft.AspNet.IISPlatformHandler

### PR DESCRIPTION
**Pull request by alexbocharov**
Switching to new ‘dotnet’ target framework monikers (https://github.com/aspnet/Announcements/issues/98)

### CODE REVIEW

**Comment by davidfowl** [comment]
@alexbocharov can you squash your commits

**Comment by alexbocharov** [comment]
@davidfowl, I squashed my commits

**Comment by davidfowl** [comment]
I assume you also saw the CLA messages 😀

**Comment by alexbocharov** [comment]
@davidfowl 
Of course, I went through all the steps. Got Contribution License. Maybe something I did wrong?
(Sorry for my English 😀)

**Comment by moozzyk** [comment]
Will merge. 
@Eilon - what can be the reason of cla-required not being cleared out?

**Comment by alexbocharov** [comment]
Resolving conflicts

**Comment by Eilon** [comment]
The bot might have had a hiccup, so I removed the bad label.

**Pull request merged**
