### PR TITLE
Add AppVeyor, Travis build status

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by Eilon** [comment]
It doesn't look like AppVeyor is set up for this repo...

**Comment by hishamco** [comment]
You can make this PR open until someone set up AppVeyor for this repo, or close it

**Comment by Eilon** [comment]
Token: `rx21cyyt494kak2v`

**Comment by hishamco** [comment]
The PR has been updated

thanks @Eilon

**Pull request merged**
