### PR TITLE
Fixing the signalr resource issue.

### PR DESCRIPTION
**Pull request by Praburaj**
Currently throws an error when resource is read.

@victorhurdugaci

### CODE REVIEW

**Comment by victorhurdugaci** [comment]
already fixed: https://github.com/aspnet/SignalR-Server/pull/97

**Comment by Praburaj** [comment]
@victorhurdugaci Are these the same. I thought this fix is for all the string resources in signalr?

**Comment by davidfowl** [comment]
Why do we need named resources here?

**Comment by victorhurdugaci** [comment]
We don't need this PR at all

**Comment by victorhurdugaci** [comment]
@Praburaj yes, it is the same fix. There were two possible fixes: update code to match the name of the resources or rename the resource, using named resources, to match the code. We took the first approach.

**Comment by Praburaj** [comment]
sounds good. closing this PR.

**Pull request closed without merging**
